# Generated by Django 4.2 on 2023-05-31 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defect', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='opinion',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='reporter',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
