# Generated by Django 4.2 on 2023-05-31 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defect', '0003_report_opinion_report_reporter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ikco_id', models.CharField(max_length=100)),
                ('technical_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='fault',
            old_name='solution',
            new_name='file',
        ),
        migrations.AddField(
            model_name='report',
            name='piece',
            field=models.ManyToManyField(to='defect.piece'),
        ),
    ]
