# Generated by Django 4.2 on 2023-05-31 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defect', '0004_piece_rename_solution_fault_file_report_piece'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='startTime',
            field=models.TimeField(),
        ),
    ]
