# Generated by Django 4.2 on 2023-06-07 05:46

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('defect', '0005_alter_report_starttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date',
            field=django_jalali.db.models.jDateField(),
        ),
    ]
