# Generated by Django 4.2 on 2023-06-07 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defect', '0006_alter_report_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='piece',
            field=models.ManyToManyField(null=True, to='defect.piece'),
        ),
    ]
