# Generated by Django 4.2 on 2023-06-07 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defect', '0007_alter_report_piece'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='piece',
            field=models.ManyToManyField(blank=True, null=True, to='defect.piece'),
        ),
        migrations.AlterField(
            model_name='report',
            name='stopTime',
            field=models.TimeField(blank=True),
        ),
    ]
