# Generated by Django 4.2 on 2023-06-07 11:27

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('defect', '0008_alter_report_date_alter_report_piece_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date',
            field=django_jalali.db.models.jDateField(),
        ),
    ]
