# Generated by Django 4.2 on 2023-06-14 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('defect', '0010_piece_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='fault',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='defect.fault'),
        ),
        migrations.AlterField(
            model_name='report',
            name='opinion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='reporter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
